### PR TITLE
App Localization

### PR DESCRIPTION
**Pull request by RogerUP13**
#3 
Hi! I would like to suggest a way to translate the app to different languages.

### CODE REVIEW

**Comment by RogerUP13** [comment]
New translation can be added using following steps:
1) Add new resource file into Localization folder with suffix from [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
изображение

2) Copy all existing strings from Strings.resx file to the new file
3) Translate a text in 'Value' column

Language of the application will be selected automatically based on windows language.

As an example I translated the app to Russian.

**Comment by RogerUP13** [comment]
Translation can be delegated to different person.
He or she have to download the file XB1ControllerBatteryIndicator/XB1ControllerBatteryIndicator/Localization/Strings.resx and translate all values in data elements
изображение
And then some how provide translated file to @NiyaShy

**Comment by NiyaShy** [comment]
Hey,
thanks for the pull request, this looks very promising. There's just one thing that bugs me: automatic selection of the language based on your system language. While it's nice to have, there might be others like me who prefer to run certain programs in a language that differs from their system (in my case, German system, but I run quite a few programs in English). 
Ideally, it would be nice if it would pick the language based on your system by default, but you are still able to change it yourself via the context menu.

**Comment by RogerUP13** [comment]
Thanks. I'll try to add this improvement.

**Comment by RogerUP13** [comment]
Hi. Now the language can be changed manually. The selected language is saved in the settings.
изображение

**Comment by NiyaShy** [comment]
Perfect, works like a charm. Thanks a lot for your work!

**Pull request merged**
