### PR TITLE
Battery Level Popup

### PR DESCRIPTION
**Pull request by Friday-The13-rus**
Found that #46 idea sounds brilliant and would like to provide the implementation.
изображение
Includes implementation of the popup and settings window.
On the settings window display duration, position and size, colors and font can be changed based on personal preferences.
изображение
Added a couple of items in context menu that allow to enable/disable popup and toast message.
And additional setting to display popup in any time regardless of battery level using XBox button.

I translated text in the popup to all supported languages (because of it is almost the same as message in the toast), but new context menu items and the settings window are translated only to English and Russian.

The pull request contains a lot of code, but the biggest part is for the settings window.

### CODE REVIEW

**Comment by MorbidEden** [comment]
This implementation is excellent. Great work. I only found one issue: when powering off the controller with the "Show Popup on pressing XBox button" option enabled, holding down the XBox button prompts the popup to show repeatedly as if it is "flickering." Otherwise, this is great.

**Comment by Friday-The13-rus** [comment]
@MorbidEden thanks. I thought about it. Changed event for displaying the pop up from press to release the button.

**Comment by NiyaShy** [comment]
Consider my jaw dropped 😮 This looks really nice and like a great implementation. 
BUT: Haven't written it down anywhere yet (or enforced it through github), but pushing such rather big changes directly to the master branch is a big no-no. The testing branch is there for a reason so new features can be tried out without messing up the main code. I know that I've allowed it in the past, but that will change.

**Comment by Friday-The13-rus** [comment]
I got your point.  Not sure that the testing branch is up to date, but I will update target branch.

**Comment by NiyaShy** [comment]
It currently is slightly behind, but only by 2 translations that recently got added. So nothing game breaking.
Thanks for changing it, I'll see that those conflicts get resolved so it can be merged. And ofc thanks a bunch for coding this 😃

**Comment by MorbidEden** [comment]
@Friday-The13-rus Seems to be working perfectly now. Thank you for your work.

@NiyaShy Thank you for all of your work on this, as well. I've been using this for a couple of years and it's quite essential for QoL.

**Comment by NiyaShy** [comment]
Hm... From the reported 6 conflicts the first 5 were harmless (simple additions). But the ViewModel might become a nut to crack due to the changes rolodato submitted with #39. I'll have to check if I can resolve the overlapping changes without breaking anything...

**Comment by Friday-The13-rus** [comment]
Merged with features in the testing, including #39

**Comment by NiyaShy** [comment]
Thanks, that saved me a bit of a headache 😉 Conflict resolution on Github isn't very helpful, and my VS is currently a bit "messed up" due to experiments with migrating to .net core...

**Comment by MorbidEden** [comment]
@NiyaShy I have a very vanilla install of VS Community 2019 16.8.2 with only ".NET desktop development" and "Desktop development with C++" if you need testing help.

**Comment by blackhorse088** [comment]
This is so amazing! Can't wait to try it out!

A note here got my attention, are the X button unique to each controller? Which means, if Controller 2 pressed it, it shows Controller 2 status? And what about Gamebar?
Trying to help avoiding any conflictions.

If any graphical assistance needed, of any kind, let me know! Will be glad to help :)
Thank you Friday-The13-rus, NiyaShy and everyone for this amazing work!

**Pull request merged**
